ebook_metadata:
  title: ༄༅། །རྨད་བྱུང་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  sku: SHE-SHAP-07
  layers:
  - book_title
  - author
  - quotation
  - yigchung
web_metadata:
  title:
    en: The Book of Wondrous Emanated Scriptures
    bo: རྨད་བྱུང་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 7
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༧
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-07
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-07.epub
  description:
    en: ''
    bo: ''
